mxid: '@the-loan-wolf:matrix.org'
device_id: BZDFWZDPSW
access_token: syt_dGhlLWxvYW4td29sZg_QQDQRDvsfMlitJKvXDCo_2qsxJN
homeserver: https://matrix-client.matrix.org/
room_cache_size: 32
room_cache_age: 60
notify_sound: true
send_to_verified_only: false
backspace1_removes_word: true
backspace2_removes_word: false
always_clear_screen: true
data_dir: /data/data/com.termux/files/home/.local/share/gomuks
cache_dir: /data/data/com.termux/files/home/.cache/gomuks
history_path: /data/data/com.termux/files/home/.cache/gomuks/history.db
room_list_path: /data/data/com.termux/files/home/.cache/gomuks/rooms.gob.gz
media_dir: /data/data/com.termux/files/home/.cache/gomuks/media
download_dir: /data/data/com.termux/files/home/Downloads
state_dir: /data/data/com.termux/files/home/.cache/gomuks/state
